import React from "react";
import Head from "next/head";

type Props = {
  children: string;
};

const HeadContainer = ({ children }: Props) => {
  return (
    <Head>
      <title>{children as string} | GenFig</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};

export default HeadContainer;
